apiVersion: aws.platformref.upbound.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: platform-ref-aws-db
spec:
  parameters:
    storageGB: 5
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    clusterRef:
      id: platform-ref-aws
  writeConnectionSecretToRef:
    name: platform-ref-aws-db-conn
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque
